### ISSUE TITLE
QhX/utils/mock_lc.py - period calculation issue

### ISSUE THREAD

**Issue by aheranval** [lionandjelka/QhX1#11]
Hi, I noticed what looks like an issue in the code and wanted to bring it up - in mock_lc.artificial_stochastic_mock_lc() the period gets calculated (`P = np.sqrt(((lightdays*conver)**3)/(msmbh))`) and then immediately gets reassigned to a value of 0.001. Thank you, hope it is helpful!

The specific code:

```
# Calculate underlying periodicity
conver=173.145 # convert from LightDays to AU
lightdays=10
P = np.sqrt(((lightdays*conver)**3)/(msmbh))
# Calculating and adding oscillatory signal
P = 0.001 ### this seems like an issue
sinus=A*np.sin(2*np.pi*tt*(P*365)) # as a consequence here P = 0.001
```

**Comment by lionandjelka** [comment]
Hi Alice,

Thank you for your efforts and message. We have updated the function to allow users to choose between using their own hard-coded values or physical periods. However, users will need to manage this setting within the function parameters.
Kind regards
Angelica
